name: MLflow CI Skilled

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Miniconda
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.12
          auto-activate-base: true

      # 3. Create conda environment
      - name: Create conda environment
        run: |
          conda env create -f MLProject/conda.yaml
          conda info --envs
          
      # 4. Activate environment and install MLflow
      - name: Activate environment & install MLflow
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate mlflow-env
          pip install --upgrade mlflow

      # 5. Set MLflow Tracking URI
      - name: Set MLflow Tracking URI
        run: echo "MLFLOW_TRACKING_URI=mlruns" >> $GITHUB_ENV

      # 6. Run MLflow Project
      - name: Run MLflow Project
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate mlflow-env
          mlflow run MLProject -P data_path="MLProject/heart_preprocessing/data.clean.csv"

      # 7. Commit artefak model ke GitHub
      - name: Commit MLflow artifacts
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add MLProject/artifacts
          git commit -m "Add MLflow model artifacts [ci skip]" || echo "No changes to commit"
          git push
