name: MLflow CI Skilled

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Miniconda
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.12
          auto-activate-base: true

      # 3. Create conda environment
      - name: Create conda environment
        run: conda env create -f MLProject/conda.yaml

      # 4. Activate environment & install MLflow
      - name: Activate env & install MLflow
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate mlflow-env
          pip install --upgrade mlflow

      # 5. Set MLflow tracking URI
      - name: Set MLflow Tracking URI
        run: echo "MLFLOW_TRACKING_URI=mlruns" >> $GITHUB_ENV

      # 6. Run MLflow Project
      - name: Run MLflow Project
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate mlflow-env
          mlflow run MLProject -P data_path="MLProject/heart_preprocessing/data.clean.csv" --env-manager local

      # 7. Upload artefak model sebagai GitHub Actions artifact
      - name: Upload MLflow artefacts
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-artifacts
          path: MLProject/artifacts
